language: node_js

sudo: false

notifications:
  email: false

node_js:
  - "4.3.2"

after_success: npm run coveralls

script:
  - npm test-travis

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
